#!/usr/bin/env python

import argparse
import sys
import subprocess




def main(argv=None):
    
	parser = argparse.ArgumentParser(description='Run a program repeatedly and compute average reported runtime. Two throwaway runs are done before the specified number of runs are performed.')
	parser.add_argument('nruns', help='number of times to run the program')
	parser.add_argument('program', nargs=argparse.REMAINDER, help='the program to run, along with any arguments')
	args = parser.parse_args()

	nruns = int(args.nruns)
	cmdline = " ".join(["/bin/sh -c \""] + args.program + ["|", "grep", "%%%","\"", "; exit 0 "])
	
#	print cmdline 
	output = subprocess.check_output(cmdline, shell=True)
	
#	print output
	
	timeunits = output.split()[3]
	subprocess.check_call(cmdline, shell=True)	
	
	total = 0
	for i in range(nruns):
		output = subprocess.check_output(cmdline, shell=True)
#		print output
		runtime = float(output.split()[2])
#		print runtime
		total += runtime
	
	average = total/nruns	
	print ("Average execution time over %(nruns)d runs was %(average).3f %(timeunits)s" % locals())
	



	
if __name__ == "__main__":
    sys.exit(main())
